[project]
name = "mcp-baostock-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "baostock>=0.8.9",
    "fastapi>=0.68.0",
    "mcp[cli]>=1.6.0",
    "uvicorn>=0.15.0",
    "pandas>=1.3.0"
]

[tool.poetry]
name = "baostock-mcp"
version = "0.1.0"
description = "BaoStock MCP Server"
authors = ["会读论文的小仙女<huggingai666@gmail.com>"]

[tool.poetry.dependencies]
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
baostock = "^0.8.9"
pandas = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mcp-baostock-server = "mcp_baostock_server.server:main"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_baostock_server"]
